version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: recycling_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootp
      MYSQL_DATABASE: recycling_points
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: recycling_admin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
    depends_on:
      - db