/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ApiTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = ApiTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['contrasena', 'correoElectronico', 'estaActivo', 'fechaActualizacion', 'fechaCreacion', 'id', 'nombreCompleto', 'puntosAcumulados', 'rol'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare contrasena: string
  @column()
  declare correoElectronico: string
  @column()
  declare estaActivo: boolean | null
  @column.dateTime()
  declare fechaActualizacion: DateTime | null
  @column.dateTime()
  declare fechaCreacion: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombreCompleto: string
  @column()
  declare puntosAcumulados: number | null
  @column()
  declare rol: string | null
}
