/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class AliadoSchema extends BaseModel {
  static $columns = ['correo', 'createdAt', 'id', 'nombreNegocio', 'password', 'rol', 'updatedAt'] as const
  $columns = AliadoSchema.$columns
  @column()
  declare correo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombreNegocio: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rol: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ApiTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'lastUsedAt', 'name', 'tokenableId', 'type', 'updatedAt'] as const
  $columns = ApiTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastUsedAt: DateTime | null
  @column()
  declare name: string | null
  @column()
  declare tokenableId: number | null
  @column()
  declare type: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class PuntoSchema extends BaseModel {
  static $columns = ['createdAt', 'direccion', 'id', 'nombre', 'updatedAt'] as const
  $columns = PuntoSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare direccion: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class UsuarioSchema extends BaseModel {
  static $columns = ['correo', 'createdAt', 'estaActivo', 'id', 'nombre', 'password', 'rol', 'telefono', 'updatedAt'] as const
  $columns = UsuarioSchema.$columns
  @column()
  declare correo: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime | null
  @column()
  declare estaActivo: boolean | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare nombre: string
  @column({ serializeAs: null })
  declare password: string
  @column()
  declare rol: string | null
  @column()
  declare telefono: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}
